export default {
    "patterns": [
        {
            "free": false,
            "id": 909820,
            "name": "Clean Lines",
            "permalink": "clean-lines-2",
            "personal_attributes": null,
            "first_photo": {
                "id": 82970190,
                "sort_order": 1,
                "x_offset": 0,
                "y_offset": 0,
                "square_url": "https://images4-e.ravelrycache.com/uploads/stitchnerd/611130017/stitchnerd-023_square.jpg",
                "medium_url": "https://images4-b.ravelrycache.com/uploads/stitchnerd/611130017/stitchnerd-023_medium.jpg",
                "thumbnail_url": "https://images4-e.ravelrycache.com/uploads/stitchnerd/611130017/stitchnerd-023_thumbnail.jpg",
                "small_url": "https://images4-e.ravelrycache.com/uploads/stitchnerd/611130017/stitchnerd-023_small_best_fit.jpg",
                "medium2_url": "https://images4-e.ravelrycache.com/uploads/stitchnerd/611130017/stitchnerd-023_medium2.jpg",
                "small2_url": "https://images4-e.ravelrycache.com/uploads/stitchnerd/611130017/stitchnerd-023_small2.jpg",
                "caption": null,
                "caption_html": null,
                "copyright_holder": "larahempsallphoto"
            },
            "designer": {
                "crochet_pattern_count": 0,
                "favorites_count": 5304,
                "id": 36637,
                "knitting_pattern_count": 259,
                "name": "Susan Ashcroft",
                "patterns_count": 259,
                "permalink": "susan-ashcroft",
                "users": [
                    {
                        "id": 992638,
                        "username": "stitchnerd",
                        "tiny_photo_url": "https://avatars-d.ravelrycache.com/stitchnerd/408045172/view_tiny.JPG",
                        "small_photo_url": "https://avatars-d.ravelrycache.com/stitchnerd/408045172/view_small.JPG",
                        "photo_url": "https://avatars-d.ravelrycache.com/stitchnerd/408045172/view_large.JPG"
                    }
                ]
            },
            "pattern_author": {
                "crochet_pattern_count": 0,
                "favorites_count": 5304,
                "id": 36637,
                "knitting_pattern_count": 259,
                "name": "Susan Ashcroft",
                "patterns_count": 259,
                "permalink": "susan-ashcroft",
                "users": [
                    {
                        "id": 992638,
                        "username": "stitchnerd",
                        "tiny_photo_url": "https://avatars-d.ravelrycache.com/stitchnerd/408045172/view_tiny.JPG",
                        "small_photo_url": "https://avatars-d.ravelrycache.com/stitchnerd/408045172/view_small.JPG",
                        "photo_url": "https://avatars-d.ravelrycache.com/stitchnerd/408045172/view_large.JPG"
                    }
                ]
            },
            "pattern_sources": [
                {
                    "amazon_rating": null,
                    "amazon_reviews": null,
                    "amazon_sales_rank": null,
                    "amazon_updated_at": null,
                    "amazon_url": null,
                    "approved_patterns_count": 228,
                    "asin": "",
                    "author": "",
                    "author_pattern_author_id": null,
                    "author_surname": "",
                    "book_binding": null,
                    "completed": false,
                    "created_at": "2012/05/25 14:04:55 -0400",
                    "designer_pending_patterns_count": 0,
                    "designer_users_count": 4,
                    "editorships_count": 1,
                    "favorites_count": 464,
                    "first_photo_id": 23940694,
                    "flaggings_count": 0,
                    "fulfilled_by_ravelry": false,
                    "has_photo": true,
                    "id": 114905,
                    "isbn_13": "",
                    "issue": null,
                    "keywords": "",
                    "label": null,
                    "large_image_url": null,
                    "last_pattern_edit": "2019/03/06 12:24:28 -0500",
                    "link_id": 206280,
                    "list_price": null,
                    "lock_version": 5,
                    "medium_image_url": null,
                    "name": "Stitchnerd Designs",
                    "out_of_print": false,
                    "pattern_source_type_id": 7,
                    "patterns_count": 229,
                    "pending_patterns_count": 1,
                    "periodical": false,
                    "permalink": "stitchnerd-designs",
                    "photos_permitted": false,
                    "popularity": 0,
                    "popularity_rank": 2147483647,
                    "price": null,
                    "publication_date": null,
                    "publication_date_set": 0,
                    "publication_day_set": 0,
                    "publication_sort_order": null,
                    "publication_year": null,
                    "publisher_id": null,
                    "shelf_image_path": "http://images4.ravelry.com/uploads/stitchnerd/105384064/0_rainbow_flo_better_crop_shelved.jpg",
                    "shelf_image_size": "150x150",
                    "small_image_url": "http://images4.ravelry.com/uploads/stitchnerd/105384064/0_rainbow_flo_better_crop_square.jpg",
                    "source_group_id": null,
                    "stickies_count": 1,
                    "store_id": 16192,
                    "updated_at": "2014/02/15 08:19:04 -0500",
                    "url": "http://www.ravelry.com/stores/stitchnerd-designs",
                    "work_id": null,
                    "notes": ""
                }
            ]
        }, 

        {
            "free": false,
            "id": 768902,
            "name": "Audrey",
            "permalink": "audrey-30",
            "personal_attributes": null,
            "first_photo": {
                "id": 69387883,
                "sort_order": 1,
                "x_offset": 0,
                "y_offset": -43,
                "square_url": "https://images4-b.ravelrycache.com/uploads/diemercerie-muc/471198475/_PWS1479_square.jpg",
                "medium_url": "https://images4-b.ravelrycache.com/uploads/diemercerie-muc/471198475/_PWS1479_medium.jpg",
                "thumbnail_url": "https://images4-e.ravelrycache.com/uploads/diemercerie-muc/471198475/_PWS1479_thumbnail.jpg",
                "small_url": "https://images4-b.ravelrycache.com/uploads/diemercerie-muc/471198475/_PWS1479_small_best_fit.jpg",
                "medium2_url": "https://images4-b.ravelrycache.com/uploads/diemercerie-muc/471198475/_PWS1479_medium2.jpg",
                "small2_url": "https://images4-b.ravelrycache.com/uploads/diemercerie-muc/471198475/_PWS1479_small2.jpg",
                "caption": null,
                "caption_html": null,
                "copyright_holder": null
            },
            "designer": {
                "crochet_pattern_count": 0,
                "favorites_count": 74,
                "id": 77715,
                "knitting_pattern_count": 63,
                "name": "Die Mercerie",
                "patterns_count": 63,
                "permalink": "die-mercerie",
                "users": [
                    {
                        "id": 1914615,
                        "username": "diemercerie-muc",
                        "tiny_photo_url": "https://avatars-d.ravelrycache.com/sniebler/154408971/Mercerie_60x60_tiny.png",
                        "small_photo_url": "https://avatars-d.ravelrycache.com/sniebler/154408971/Mercerie_60x60_small.png",
                        "photo_url": "https://avatars-d.ravelrycache.com/sniebler/154408971/Mercerie_60x60_large.png"
                    }
                ]
            },
            "pattern_author": {
                "crochet_pattern_count": 0,
                "favorites_count": 74,
                "id": 77715,
                "knitting_pattern_count": 63,
                "name": "Die Mercerie",
                "patterns_count": 63,
                "permalink": "die-mercerie",
                "users": [
                    {
                        "id": 1914615,
                        "username": "diemercerie-muc",
                        "tiny_photo_url": "https://avatars-d.ravelrycache.com/sniebler/154408971/Mercerie_60x60_tiny.png",
                        "small_photo_url": "https://avatars-d.ravelrycache.com/sniebler/154408971/Mercerie_60x60_small.png",
                        "photo_url": "https://avatars-d.ravelrycache.com/sniebler/154408971/Mercerie_60x60_large.png"
                    }
                ]
            },
            "pattern_sources": [
                {
                    "amazon_rating": null,
                    "amazon_reviews": null,
                    "amazon_sales_rank": null,
                    "amazon_updated_at": null,
                    "amazon_url": null,
                    "approved_patterns_count": 47,
                    "asin": "",
                    "author": "Die Mercerie",
                    "author_pattern_author_id": 77715,
                    "author_surname": "Mercerie",
                    "book_binding": null,
                    "completed": false,
                    "created_at": "2015/06/27 14:02:51 -0400",
                    "designer_pending_patterns_count": 0,
                    "designer_users_count": 0,
                    "editorships_count": 0,
                    "favorites_count": 17,
                    "first_photo_id": null,
                    "flaggings_count": 0,
                    "fulfilled_by_ravelry": false,
                    "has_photo": false,
                    "id": 191109,
                    "isbn_13": null,
                    "issue": null,
                    "keywords": "",
                    "label": null,
                    "large_image_url": null,
                    "last_pattern_edit": "2019/02/04 12:32:00 -0500",
                    "link_id": 377341,
                    "list_price": null,
                    "lock_version": 10,
                    "medium_image_url": null,
                    "name": "Die Mercerie on Ravelry",
                    "out_of_print": false,
                    "pattern_source_type_id": 7,
                    "patterns_count": 52,
                    "pending_patterns_count": 5,
                    "periodical": false,
                    "permalink": "die-mercerie-on-ravelry",
                    "photos_permitted": false,
                    "popularity": 0,
                    "popularity_rank": 2147483647,
                    "price": null,
                    "publication_date": null,
                    "publication_date_set": 0,
                    "publication_day_set": 0,
                    "publication_sort_order": null,
                    "publication_year": null,
                    "publisher_id": null,
                    "shelf_image_path": null,
                    "shelf_image_size": null,
                    "small_image_url": null,
                    "source_group_id": null,
                    "stickies_count": 1,
                    "store_id": 36342,
                    "updated_at": "2017/10/02 12:20:06 -0400",
                    "url": "https://www.ravelry.com/stores/die-mercerie-2",
                    "work_id": null,
                    "notes": ""
                }
            ]
        },
        {
            "free": false,
            "id": 909555,
            "name": "Get Together Wrap",
            "permalink": "get-together-wrap",
            "personal_attributes": null,
            "first_photo": {
                "id": 82985715,
                "sort_order": 1,
                "x_offset": -43,
                "y_offset": 0,
                "square_url": "https://images4-e.ravelrycache.com/uploads/jojilocat/611258711/WN7A3590_square.jpg",
                "medium_url": "https://images4-b.ravelrycache.com/uploads/jojilocat/611258711/WN7A3590_medium.jpg",
                "thumbnail_url": "https://images4-e.ravelrycache.com/uploads/jojilocat/611258711/WN7A3590_thumbnail.jpg",
                "small_url": "https://images4-b.ravelrycache.com/uploads/jojilocat/611258711/WN7A3590_small_best_fit.jpg",
                "medium2_url": "https://images4-b.ravelrycache.com/uploads/jojilocat/611258711/WN7A3590_medium2.jpg",
                "small2_url": "https://images4-e.ravelrycache.com/uploads/jojilocat/611258711/WN7A3590_small2.jpg",
                "caption": null,
                "caption_html": null,
                "copyright_holder": null
            },
            "designer": {
                "crochet_pattern_count": 0,
                "favorites_count": 22678,
                "id": 16057,
                "knitting_pattern_count": 211,
                "name": "Joji Locatelli",
                "patterns_count": 211,
                "permalink": "joji-locatelli",
                "users": [
                    {
                        "id": 99736,
                        "username": "jojilocat",
                        "tiny_photo_url": "https://avatars-d.ravelrycache.com/jojilocat/503176464/27577271_2061610687418453_3204826921791651840_n_tiny.jpg",
                        "small_photo_url": "https://avatars-d.ravelrycache.com/jojilocat/503176464/27577271_2061610687418453_3204826921791651840_n_small.jpg",
                        "photo_url": "https://avatars-d.ravelrycache.com/jojilocat/503176464/27577271_2061610687418453_3204826921791651840_n_large.jpg"
                    }
                ]
            },
            "pattern_author": {
                "crochet_pattern_count": 0,
                "favorites_count": 22678,
                "id": 16057,
                "knitting_pattern_count": 211,
                "name": "Joji Locatelli",
                "patterns_count": 211,
                "permalink": "joji-locatelli",
                "users": [
                    {
                        "id": 99736,
                        "username": "jojilocat",
                        "tiny_photo_url": "https://avatars-d.ravelrycache.com/jojilocat/503176464/27577271_2061610687418453_3204826921791651840_n_tiny.jpg",
                        "small_photo_url": "https://avatars-d.ravelrycache.com/jojilocat/503176464/27577271_2061610687418453_3204826921791651840_n_small.jpg",
                        "photo_url": "https://avatars-d.ravelrycache.com/jojilocat/503176464/27577271_2061610687418453_3204826921791651840_n_large.jpg"
                    }
                ]
            },
            "pattern_sources": [
                {
                    "amazon_rating": null,
                    "amazon_reviews": null,
                    "amazon_sales_rank": null,
                    "amazon_updated_at": null,
                    "amazon_url": null,
                    "approved_patterns_count": 131,
                    "asin": "",
                    "author": "",
                    "author_pattern_author_id": null,
                    "author_surname": "",
                    "book_binding": null,
                    "completed": false,
                    "created_at": "2008/09/10 13:15:47 -0400",
                    "designer_pending_patterns_count": 0,
                    "designer_users_count": 30,
                    "editorships_count": 2,
                    "favorites_count": 1728,
                    "first_photo_id": 33816388,
                    "flaggings_count": 0,
                    "fulfilled_by_ravelry": false,
                    "has_photo": true,
                    "id": 28810,
                    "isbn_13": "",
                    "issue": null,
                    "keywords": "",
                    "label": null,
                    "large_image_url": null,
                    "last_pattern_edit": "2019/03/06 07:23:09 -0500",
                    "link_id": 204420,
                    "list_price": null,
                    "lock_version": 16,
                    "medium_image_url": null,
                    "name": "J O J I",
                    "out_of_print": false,
                    "pattern_source_type_id": 7,
                    "patterns_count": 175,
                    "pending_patterns_count": 44,
                    "periodical": false,
                    "permalink": "j-o-j-i",
                    "photos_permitted": false,
                    "popularity": 0,
                    "popularity_rank": 866,
                    "price": null,
                    "publication_date": null,
                    "publication_date_set": 0,
                    "publication_day_set": 0,
                    "publication_sort_order": null,
                    "publication_year": null,
                    "publisher_id": null,
                    "shelf_image_path": "http://images4.ravelry.com/uploads/jojilocat/180502513/Joji-Logo_square_shelved.jpg",
                    "shelf_image_size": "150x150",
                    "small_image_url": "http://images4.ravelry.com/uploads/jojilocat/180502513/Joji-Logo_square_square.jpg",
                    "source_group_id": null,
                    "stickies_count": 4,
                    "store_id": 2541,
                    "updated_at": "2017/09/25 16:15:15 -0400",
                    "url": "http://www.ravelry.com/stores/j-o-j-i",
                    "work_id": null,
                    "notes": ""
                }
            ]
        }
    ]
};